name: “GET bolsonaro.cc”

# gatilhos: você pode usar push, schedule, workflow_dispatch etc.
on:
  push:
    branches:
      - main

jobs:
  call-bolsonaro:
    runs-on: ubuntu-latest
    steps:
      # (opcional) faz checkout do código, caso você queira usar arquivos do repositório
      - uses: actions/checkout@v4

      # passo que executa o curl
      - name: “Faz GET em bolsonaro.cc”
        run: |
          echo "Enviando requisição GET para bolsonaro.cc..."
          curl -v -X GET https://bolsonaro.cc
